---
**Task 1.** У тебе є дані по користувачу за два дні:

- **День 1**: вектор `v1 = (перегляди, лайки, коментарі) = (10, 3, 1)`
- **День 2**: `v2 = (7, 5, 0)`

In [3]:
import numpy as np

v1 = np.array([10, 3, 1])
v2 = np.array([7, 5, 0])

# use operation + in numpy 
# code

ans = v1 + v2
print(ans)

[17  8  1]


---
Task 1.1 
Дані
У користувача є активність за 3 дні:

- День 1 → `v1 = (12 переглядів, 3 лайки, 1 коментар)`
- День 2 → `v2 = (20, 5, 0)`
- День 3 → `v3 = (8, 2, 1)`

In [5]:
import numpy as np

v1 = np.array([12, 3, 1])
v2 = np.array([20, 5, 0])
v3 = np.array([8, 2, 1])

ans = v1 + v2 + v3
ans 
# use operation + in numpy 
# code

array([40, 10,  2])

---
**Task 2.** Є два користувачі зі схожого сегменту:

> u1 = (перегляди, лайки, підписки) = (30, 4, 1) \
> u2 = (20, 6, 0)

Потрібно зрозуміти, чим відрізняється їхня поведінка.

In [6]:
import numpy as np

u1 = np.array([30, 4, 1])
u2 = np.array([20, 6, 0])


print(u1 - u2)

# use operation - in numpy
# code

[10 -2  1]


---
**Task 2.2**
Поведінка користувача за 2 тижні:

Тиждень 1 → w1 = (100 переглядів, 15 лайків, 3 підписки)

Тиждень 2 → w2 = (140, 18, 5)

In [14]:
import numpy as np

w1 = np.array([100, 15, 3])
w2 = np.array([140, 18, 5])

print(w1 - w2)
# use operation - in numpy

[-40  -3  -2]


---
**Task 3.1**  З’ясувати, хто “сильніший” за загальною активністю.

Два користувачі: \
u1 = (50 переглядів, 10 лайків, 4 підписки) \
u2 = (70, 5, 1)



In [ ]:
import numpy as np

u1 = np.array([50, 10, 4])
u2 = np.array([70, 5, 1])

print(np.linalg.norm(u1))
print(np.linalg.norm(u2))



# use linalg.norm

51.146847410177685
70.18546858146635


---
**Task 4.** Двоє користувачів у просторі ознак:

> u1 = (перегляди, лайки) = (10, 2) \
> u2 = (15, 5)

Потрібно:
> знайти відстань між ними (евклідова), \
> зрозуміти, хто “активніший” у загальному масштабі.

In [ ]:
# 1. Відстань між користувачами

# use np.linalg.norm
# code 
u1 = np.array([50, 10, 4])
u2 = np.array([70, 5, 1])

distance = np.linalg.norm(u1 - u2) # Обчислюємо відстань між двома векторами (користувачами)

print(f"Відстань між двома векторами {distance}")
# print(np.linalg.norm(u2))



# 2. Рівень активності кожного (довжина вектора)
# use np.linalg.norm
# code 
vector_length_u1 = np.linalg.norm(u1) # Pівень активності кожного / довжина вектора u1
vector_length_u2 = np.linalg.norm(u2) # Pівень активності кожного / довжина вектора u2

print(f"довжини векторів {vector_length_u1}, {vector_length_u2}")

Відстань між двома векторами 20.83266665599966
довжини векторів 51.146847410177685, 70.18546858146635


---
**Task 5.** Нормалізація поведінкових фіч перед кластеризацією


In [ ]:
import numpy as np

users = np.array([
    [10, 3, 1],
    [40, 2, 0],
    [20, 5, 2],
    [15, 1, 1],
    [60, 7, 3]
])

users_norm = np.linalg.norm(users, axis=1) # Обчислюємо норму (довжину вектора) ДЛЯ КОЖНОГО користувача, axis=1 означає: обробляємо по рядках

# use linalg.norm
# users / by previos step
users_normalized = users / users_norm.reshape(-1, 1) # Нормалізація — ділимо кожен рядок на його норму, Використовуємо reshape, щоб отримати колонку (5,1). # .reshape(-1, 1) — це зміна форми масиву, щоб зробити його стовпчиком, а не рядком.
print(users_normalized)

[[0.95346259 0.28603878 0.09534626]
 [0.99875234 0.04993762 0.        ]
 [0.9656091  0.24140227 0.09656091]
 [0.99558497 0.06637233 0.06637233]
 [0.99204049 0.11573806 0.04960202]]


In [ ]:
# або

users_norm = np.linalg.norm(users, axis=1, keepdims=True) # Обчислюємо норму (довжину вектора) ДЛЯ КОЖНОГО користувача, axis=1 означає: обробляємо по рядках. keepdims=True — це параметр у NumPy, який каже зберегти ті ж самі розміри масиву, навіть якщо ти робиш операцію, яка зазвичай їх зменшує.

# use linalg.norm
# users / by previos step
users_normalized = users / users_norm # Нормалізація — ділимо кожен рядок на його норму, Використовуємо reshape, щоб отримати колонку (5,1)
print(users_normalized)

---
**Task 5.** Оцініть наскільки користувачу підходить товар

In [47]:
# user data 
u = (0.2, 0.8, 0.3, 0.1)

# product data
p = (0.25, 0.75, 0.2, 0.15)


import numpy as np


score = np.dot(u, p) # рахуємо скалярний добуток
print(score)

vector_length_u = np.linalg.norm(u) # рахуємо довжену вектора
vector_length_p = np.linalg.norm(p) # рахуємо довжену вектора

cos_sim = score / (vector_length_u * vector_length_p) # рахужмо косинусну схожість
print(cos_sim)

0.7250000000000002
0.9900436758984326


In [48]:
# або 

def cos_sim(a, b):
    return np.dot(a,b) / (np.linalg.norm(a) * np.linalg.norm(b))
print(cos_sim(u,p))

0.9900436758984326
