### Practise: Matrix
#### Date: 2025-12-12


In [113]:
# Task 0.1. Create zero matrix size 5x3
import numpy as np

# use zerous 
ans = np.zeros((5, 3)) #Створює матрицю 5 × 3, заповнену нулями.
print(ans)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [114]:
# Task 0.1.1. У тебе є матриці розмірів: A: 3×2 B: 2×4
# Питання.Чи можна множити A · B? Який розмір результату?

A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

# Матриця B розміром 2×4
B = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

# Множення A · B
C = np.dot(A, B)
print(C)


[[11 14 17 20]
 [23 30 37 44]
 [35 46 57 68]]


In [115]:
# Task 0.1.2. Зробити множення та перевірити чи можливо його зробити?
A = np.array([
    [10, 20],
    [15, 25],
    [30, 10]
])  

B = np.array([
    [0.6],
    [0.4]
])  
print(A, B, A.shape, B.shape)
if A.shape[1] != B.shape[0]:
    raise ValueError('No equal size')
ans = A@B
print(ans, ans.shape)
# use @ Помнож матриці саме за допомогою оператора @, а не через np.dot чи цикли”



[[10 20]
 [15 25]
 [30 10]] [[0.6]
 [0.4]] (3, 2) (2, 1)
[[14.]
 [19.]
 [22.]] (3, 1)


In [116]:
# Task 0.2. Create ones matrix size 3, 1
print('# use eye')
a = np.eye(3,3)
print(a)
print('# use ones')
b = np.ones((3,3))
print(b)

# use eye
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
# use ones
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [117]:
# Task 0.3. Dot transpose matrix . Calculate diagonal
import numpy as np

# | user | sessions | watch_hours | spend |
# | ---- | -------- | ----------- | ----- |
# | 1    | 5        | 10          | 100   |
# | 2    | 10       | 20          | 200   |
# | 3    | 3        | 6           | 60    |
# | 4    | 8        | 16          | 160   |

X = np.array([
    [5, 10, 100],
    [10, 20, 200],
    [3, 6, 60],
    [8, 16, 160]
])

# use .T and @
X_T = X.T @ X
print(f'транспонована на помножена матриця {X_T}')

# use by prev task np.diag
print(f'вектор {np.diag(X_T)}')


# use np.linalg.matrix_rank 
rank = np.linalg.matrix_rank(X)
print("Ранг:", rank)




транспонована на помножена матриця [[  198   396  3960]
 [  396   792  7920]
 [ 3960  7920 79200]]
вектор [  198   792 79200]
Ранг: 1


In [118]:
# Calculate weights "Обчислити ваги"
weights = np.array([0.5, 0.2, 0.01]) # Створюємо масив ваг для кожної колонки X:
impact = X * weights # Множимо кожну колонку матриці X на відповідну вагу.
# Це означає: X[:,0] * 0.5, X[:,1] * 0.2, X[:,2] * 0.01
impact # Зберігаємо результат у змінну impact — це зважені ознаки

array([[2.5, 2. , 1. ],
       [5. , 4. , 2. ],
       [1.5, 1.2, 0.6],
       [4. , 3.2, 1.6]])

In [119]:
# L2-normalize L2-нормалізація — це приведення стовпця (вектора) до довжини 1.
np.linalg.norm(X[:, 0])  # sessions # Обчислюємо L2-норму (довжину вектора) для першої колонки X — це ознака "sessions"
np.linalg.norm(X[:, 1])  # watch_hours # Обчислюємо L2-норму для другої колонки X — це ознака "watch_hours"
np.linalg.norm(X[:, 2])  # spend # Обчислюємо L2-норму для третьої колонки X — це ознака "spend"


np.float64(281.42494558940575)

In [139]:
# Task 1.
import numpy as np

X = np.array([
    [20, 5],
    [30, 10],
    [40, 20]
])

# скільки колонок? рядків? який тип матриці

print(f'матрифя складається {X.shape}')

print(X.shape)      # (3, 2)
print(type(X))      # numpy.ndarray (прямокутна матриця 3×2)

матрифя складається (3, 2)
(3, 2)
<class 'numpy.ndarray'>


In [140]:
# Task 2. Transpose matrix from task 1

# use .T
X_T = X.T
print(X_T)

[[20 30 40]
 [ 5 10 20]]


In [141]:
# Task 3. Analyze titanic - do EDA (sample, isnull, head, describe, shape, info, etc)

import seaborn as sns
import numpy as np

df = sns.load_dataset("titanic")
df_nan = df.dropna(subset=["age", "fare", "pclass", "survived"])
print(df.head())
print(df_nan.head())




   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  

In [142]:
print(df.sample(5)) # vетод sample() вибирає випадкові рядки з DataFrame
print(df_nan.sample(5))


     survived  pclass     sex   age  sibsp  parch      fare embarked   class  \
348         1       3    male   3.0      1      1   15.9000        S   Third   
52          1       1  female  49.0      1      0   76.7292        C   First   
399         1       2  female  28.0      0      0   12.6500        S  Second   
118         0       1    male  24.0      0      1  247.5208        C   First   
782         0       1    male  29.0      0      0   30.0000        S   First   

       who  adult_male deck  embark_town alive  alone  
348  child       False  NaN  Southampton   yes  False  
52   woman       False    D    Cherbourg   yes  False  
399  woman       False  NaN  Southampton   yes   True  
118    man        True    B    Cherbourg    no  False  
782    man        True    D  Southampton    no   True  
     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
21          1       2    male  34.0      0      0  13.0000        S  Second   
867         0       1    

In [143]:
print(df.isnull().sum()) #рахує кількість пустих значень в кожному рядку
print('---')
print(df_nan.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64
---
survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           530
embark_town      2
alive            0
alone            0
dtype: int64


In [144]:
print(df.describe()) #це метод, який автоматично обчислює базову статистику для числових колонок у DataFrame.
print('---')
print(df_nan.describe())

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200
---
         survived      pclass         age       sibsp       parch        fare
count  714.000000  714.000000  714.000000  714.000000  714.000000  714.000000
mean     0.406162    2.236695   29.699118    0.512605    0.431373   34.694514
std      0.491460    0.838250   14.526497    0.929783    0.8

In [145]:
print(df.shape) # Вона повертає розмір таблиці у вигляді кортежу:

print(df_nan.shape)

(891, 15)
(714, 15)


In [146]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB
None


In [147]:
print(df_nan.info())

<class 'pandas.core.frame.DataFrame'>
Index: 714 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     714 non-null    int64   
 1   pclass       714 non-null    int64   
 2   sex          714 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        714 non-null    int64   
 5   parch        714 non-null    int64   
 6   fare         714 non-null    float64 
 7   embarked     712 non-null    object  
 8   class        714 non-null    category
 9   who          714 non-null    object  
 10  adult_male   714 non-null    bool    
 11  deck         184 non-null    category
 12  embark_town  712 non-null    object  
 13  alive        714 non-null    object  
 14  alone        714 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 70.2+ KB
None


In [148]:
X = df[["age", "fare", "pclass"]].values   # Витягуємо з датафрейму df три колонки і перетворюємо їх у numpy-матрицю (ознаки X)
y = df["survived"].values 
# Витягуємо цільову змінну y (вижив чи ні) і перетворюємо у numpy-масив

X1 = df_nan[["age", "fare", "pclass"]].values   
y1 = df_nan["survived"].values      

print(np.isfinite(X).all(axis=0))  # Перевіряємо, чи всі значення у кожній колонці X є скінченними (не NaN, не inf)
print(np.isfinite(y).all())        # Перевіряємо, чи всі значення в y є скінченними

print(np.isfinite(X1).all(axis=0))  
print(np.isfinite(y1).all()) 

[False  True  True]
True
[ True  True  True]
True


In [149]:
# Task 4. Transpose matrix dot by X

# use .T and @
X_T = X.T
X1_T = X1.T
# code

XtX = X.T @ X
X1tX1 = X1.T @ X1


In [150]:
# Task 5. Масштаб ознак

# use diag method on transpose matrix
diag_val_X = np.diag(XtX)
print(diag_val_X)
print("----")
diag_val_X1 = np.diag(X1tX1)
print(diag_val_X1)

[             nan 3121864.70340831    5371.        ]
----
[ 780231.4745    2856142.9817713    4073.       ]


In [154]:
# Task 6. Перевірти ранг 
# np.linalg.matrix_rank(X) Я не можу порахувати розклад для цієї матриці, щось не так з даними».у матриці X є NaN, inf або дуже дивні значення

rank_X1 = np.linalg.matrix_rank(X1)
print(rank_X1)
# use np.linalg.matrix_rank


3


In [153]:
# Task 7. Перевірити детермінант 

# use np.linalg.det
det = np.linalg.det(X1tX1)
det

np.float64(2480946563493686.5)

In [158]:
df_nan.head(1)

survived  pclass   sex   age  sibsp  parch  fare embarked  class  who  \
0         0       3  male  22.0      1      0  7.25        S  Third  man   

   adult_male deck  embark_town alive  alone  
0        True  NaN  Southampton    no  False

In [160]:
beta = np.linalg.inv(X1tX1) @ X1.T @ y1 #Це обчислення коефіцієнтів лінійної регресії (ваг), де: X — матриця ознак, y — цільова змінна, XtX — це X.T @ X (матриця Грама). np.linalg.inv(XtX) Обчислює обернену матрицю (XᵀX)⁻¹.

beta


array([0.00337173, 0.0034799 , 0.06434391])

In [ ]:
X_norm = X1 / X1.max(axis=0) # Нормалізуємо матрицю ознак X1, ділячи кожну колонку на її максимальне значення.
# Це приводить усі ознаки до діапазону [0, 1], зберігаючи відносні пропорції.
X_norm[:5] # Виводимо перші 5 рядків нормалізованої матриці, щоб перевірити результат.

array([[0.275     , 0.01415106, 1.        ],
       [0.475     , 0.13913574, 0.33333333],
       [0.325     , 0.01546857, 1.        ],
       [0.4375    , 0.1036443 , 0.33333333],
       [0.4375    , 0.01571255, 1.        ]])

In [164]:
X_scaled = 0.01 * X1 # Масштабуємо всі значення матриці X1: зменшуємо їх у 100 разів,
# просто множачи кожен елемент на коефіцієнт 0.01.
X_scaled

array([[0.22    , 0.0725  , 0.03    ],
       [0.38    , 0.712833, 0.01    ],
       [0.26    , 0.07925 , 0.03    ],
       ...,
       [0.19    , 0.3     , 0.01    ],
       [0.26    , 0.3     , 0.01    ],
       [0.32    , 0.0775  , 0.03    ]], shape=(714, 3))